version: '3.4'

services:
  vcgrpcservice:
    image: ${DOCKER_REGISTRY-}vcgrpcservice
    build:
      context: .
      dockerfile: VcGrpcService/Dockerfile

  mongo:
    image: mongo
    restart: always
    ports:
        - 27017:27017
    volumes:
        - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
